### ISSUE TITLE
Exit our of video

### ISSUE THREAD

**Issue by robertjones1** [Mindinventory/vimeo_video_player#24]
How do you exit out of video?

**Comment by deep-mindinventory** [comment]
@robertjones1 we are not getting your question. From where do you want to exit the video? You can take the back button or anything like this. you can pop as well.

**Comment by deep-mindinventory** [comment]
Closing this issue due to no reply. Reopen if require with proper details. Thanks.

**Comment by Topiya** [comment]
I also want to exit from video player on finish, since there is an issue while calling next video method as mentioned below.

Problem: Next video is not visible if currently plying video is in full screen. Only blank screen is coming and video is plying behind blank screen so not visible),

Can any one please provide any solution to this?
