### ISSUE TITLE
Does Vimeo Player not support video chapters?

### ISSUE THREAD

**Issue by prabavgts** [Mindinventory/vimeo_video_player#39]
**### The below Vimeo video have chapters but  its doesnt show the chapeters** 

![Screenshot_20240409_145015](https://github.com/Mindinventory/vimeo_video_player/assets/67138992/30b958e6-e0dd-4057-a49a-7c2ff369b39d)

**Comment by mohit-chauhan-mi** [comment]
The library now uses an InAppWebView to play Vimeo videos, as the public config endpoint of vimeo has been deprecated and is no longer in use.

Please check out the latest [version](https://pub.dev/packages/vimeo_video_player).

@prabavgts We're using a public approach rather than the official SDK, I recommend checking out the official Vimeo Developer [documentation](https://developer.vimeo.com) for more insights on your issue.

Thanks.
