### ISSUE TITLE
Vimeo video quality

### ISSUE THREAD

**Issue by PauloReiis** [Mindinventory/vimeo_video_player#42]
Good afternoon,

I'm having trouble changing the quality of the video.

I would like to know if there is a way to change the quality of the video and if so, how do I do that?

`await dio.get(
        'https://api.vimeo.com/videos/$vimeoVideoId?fields=play',
      );`

**Comment by mohit-chauhan-mi** [comment]
The library now uses an InAppWebView to play Vimeo videos, as the public config endpoint of vimeo has been deprecated and is no longer in use.

Please check out the latest [version](https://pub.dev/packages/vimeo_video_player).

@PauloReiis We're using a public approach rather than the official SDK, I recommend checking out the official Vimeo Developer [documentation](https://developer.vimeo.com) for more insights on your issue.

Thanks.
