### ISSUE TITLE
vimeo player video not play

### ISSUE THREAD

**Issue by nikunjshaligram** [Mindinventory/vimeo_video_player#47]
![vimeo](https://github.com/user-attachments/assets/37d77bbe-fdf0-4785-9386-a2ca3ccf85be)

final String _vimeoVideoUrl = 'https://player.vimeo.com/video/videoid';

VimeoVideoPlayer(
          url: _vimeoVideoUrl,
          autoPlay: true,
        ),
        
Implement this code but video is not display. so how to resolved.

**Comment by MahmoudMagdyEllawatty** [comment]
could you solve this?

**Comment by alpeshbrainstream** [comment]
debug in fetch this error please check
Playback error
E/ExoPlayerImplInternal(15374):   androidx.media3.exoplayer.ExoPlaybackException: Source error
E/ExoPlayerImplInternal(15374):       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:717)
E/ExoPlayerImplInternal(15374):       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:689)
E/ExoPlayerImplInternal(15374):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal(15374):       at android.os.Looper.loopOnce(Looper.java:201)
E/ExoPlayerImplInternal(15374):       at android.os.Looper.loop(Looper.java:288)
E/ExoPlayerImplInternal(15374):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(15374):   Caused by: androidx.media3.datasource.FileDataSource$FileDataSourceException: java.io.FileNotFoundException: : open failed: ENOENT (No such file or directory)
E/ExoPlayerImplInternal(15374):       at androidx.media3.datasource.FileDataSource.openLocalFile(FileDataSource.java:205)
E/ExoPlayerImplInternal(15374):       at androidx.media3.datasource.FileDataSource.open(FileDataSource.java:116)
E/ExoPlayerImplInternal(15374):       at androidx.media3.datasource.DefaultDataSource.open(DefaultDataSource.java:275)
E/ExoPlayerImplInternal(15374):       at androidx.media3.datasource.StatsDataSource.open(StatsDataSource.java:86)
E/ExoPlayerImplInternal(15374):       at androidx.media3.exoplayer.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1029)
E/ExoPlayerImplInternal(15374):       at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:421)
E/ExoPlayerImplInternal(15374):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
E/ExoPlayerImplInternal(15374):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
E/ExoPlayerImplInternal(15374):       at java.lang.Thread.run(Thread.java:1012)
E/ExoPlayerImplInternal(15374):   Caused by: java.io.FileNotFoundException: : open failed: ENOENT (No such file or directory)
E/ExoPlayerImplInternal(15374):       at libcore.io.IoBridge.open(IoBridge.java:574)
E/ExoPlayerImplInternal(15374):       at java.io.RandomAccessFile.<init>(RandomAccessFile.java:289)
E/ExoPlayerImplInternal(15374):       at java.io.RandomAccessFile.<init>(RandomAccessFile.java:152)
E/ExoPlayerImplInternal(15374):       at androidx.media3.datasource.FileDataSource.openLocalFile(FileDataSource.java:186)
E/ExoPlayerImplInternal(15374):       ... 8 more
E/ExoPlayerImplInternal(15374):   Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
E/ExoPlayerImplInternal(15374):       at libcore.io.Linux.open(Native Method)
E/ExoPlayerImplInternal(15374):       at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
E/ExoPlayerImplInternal(15374):       at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
E/ExoPlayerImplInternal(15374):       at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
E/ExoPlayerImplInternal(15374):       at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7758)
E/ExoPlayerImplInternal(15374):       at libcore.io.IoBridge.open(IoBridge.java:560)
E/ExoPlayerImplInternal(15374):       ... 11 more

**Comment by IdirBelmokhtar** [comment]
I have reviewed the Vimeo API documentation and noticed some changes in the API endpoints. You can use the following dependency as a temporary solution, but please note a few conditions I encountered during testing:

- The video IDs used in the URL must support multiple qualities (SD, HD, 720, etc.).

- You need to generate a token from the Vimeo Developer portal and include it in the VimeoVideoPlayer(...) initialization.

`dependencies:`
`  vimeo_video_player:`
`    git:`
`      url: https://github.com/IdirBelmokhtar/vimeo_video_player`

**Comment by mohit-chauhan-mi** [comment]
The library now uses an InAppWebView to play Vimeo videos, as the public config endpoint of vimeo has been deprecated and is no longer in use.

@nikunjshaligram Please check this with the latest [version](https://pub.dev/packages/vimeo_video_player). Thanks.
